repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json


  - repo: https://github.com/psf/black
    rev:  stable
    hooks:
      - id: black
      - id: black-jupyter